# Generated by Django 5.2.8 on 2025-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
