# Generated by Django 5.2.8 on 2025-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_myproject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='github_repository',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
